Feature/auth into dev
Dmitry-Vasilyev/chat01 pull request #3
Opened 2024-09-08 13:33 UTC by Dmitry-Vasilyev

2024-09-08 17:16 UTC, arnokay commented on server/Application/Application.js
> +        this.tokenService = new TokenService();
надо проверить каждый класс на существование перед его инициализацией, если не существует, то использовать дефолтные.
```js
const  DefaultTokenService = require('path/to/default/token/service');
//...
this.tokenService = TokenService ? new TokenService() : new DefaultTokenService()
```

2024-09-08 17:17 UTC, arnokay commented on server/Application/Application.js
> +        this.tokenService = new TokenService();
и так со всеми.

2024-09-08 17:18 UTC, arnokay commented on server/controllers/UserController.js
> +        this.registration = this.registration.bind(this);
не уверен зачем это.

2024-09-08 17:19 UTC, arnokay commented on server/controllers/UserController.js
> +            const {email, password, nickname} = req.body;
нужно проверить все данные перед передачей их в сервис. если какого либо нет, либо они не соответсвуют формату, дать ошибку 400.

2024-09-08 17:19 UTC, arnokay commented on server/controllers/UserController.js
> +            res.cookie('refreshToken', userAuthData.refreshToken, { maxAge: 30 * 60 * 1000, httpOnly: true }); //30 min
время жизни рефреш токена нужно в переменную окружения вынести.

2024-09-08 17:20 UTC, arnokay commented on server/controllers/UserController.js
> +            console.log(e);
нужно добавить ответ при ошибке.

2024-09-08 17:21 UTC, arnokay commented on server/controllers/UserController.js
> +            res.json(userAuthData);
нет `return`.

2024-09-08 17:21 UTC, arnokay commented on server/controllers/UserController.js
> +            return res.json({message: 'Logged out'});
стандартизировать ответы. на logout можно  просто 204 без респонса.

2024-09-08 17:22 UTC, arnokay commented on server/controllers/UserController.js
> +
интересный метод.

2024-09-08 17:22 UTC, arnokay commented on server/controllers/UserController.js
> +            const {refreshToken} = req.cookies;
проверка на существование.

2024-09-08 17:26 UTC, arnokay commented on server/services/TokenService.js
> +        const {deletedCount} = await TokenModel.deleteOne({refreshToken});
количество можно не передовать. если удалило, ответ пустой, если не может удалить, потому что нет такого, дать ошибку об этом.

2024-09-08 17:29 UTC, arnokay commented on server/services/UserService.js
> +        const tokens = this.tokenService.generateToken({userDto});
нельзя добавлять в токен пароль пользователя. в токене должны быть минимальные данные для опознания юзера и полезные  данные, которые используются где-либо, всё остальное убрать. пароль никогда не возвращать, даже в хеш виде.

2024-09-08 17:30 UTC, arnokay commented on server/services/UserService.js
> +        if(!refreshToken) {
это должно быть в контроллере.

2024-09-08 17:32 UTC, arnokay commented on server/services/UserService.js
> +        if(!userData || !tokenFromDB) {
сначала проверить `userData`, после чего делать запрос на токен. сохраняем один запрос в базу.

2024-09-08 17:33 UTC, arnokay commented on server/services/UserService.js
> +        const userDB = await UserModel.findOne(userData.id);
нужно проверить вернуло ли юзера.

2024-09-08 17:34 UTC, arnokay commented on server/services/UserService.js
> +        const users = await UserModel.find();
нужно добавить пагинацию, нельзя возвращать всех всех юзеров в базе.
должен быть лимит, например 10, после чего юзер должен запрашивать кусками.

2024-09-08 17:34 UTC, arnokay commented on server/utils/HashUtil.js
> +        const saltRounds = 10;
должно быть в переменных окружения.

2024-09-08 17:35 UTC, arnokay requested changes
много комментов были указаны на одной строке, но оно относится к многим моментам, так что найти все моменты о которых говорится и исправить их.

2024-09-11 10:17 UTC, Dmitry-Vasilyev commented on server/controllers/UserController.js
> +            const {email, password, nickname} = req.body;
исправлено

2024-09-11 10:21 UTC, Dmitry-Vasilyev commented on server/controllers/UserController.js
> +            res.json(userAuthData);
исправлено

2024-09-11 10:21 UTC, Dmitry-Vasilyev commented on server/controllers/UserController.js
> +            return res.json({message: 'Logged out'});
Частично исправлено. статус поменял на 204.

2024-09-11 10:22 UTC, Dmitry-Vasilyev commented on server/controllers/UserController.js
> +            const {refreshToken} = req.cookies;
исправлено с помощью валидации

2024-09-11 10:26 UTC, Dmitry-Vasilyev commented on server/services/UserService.js
> +        const tokens = this.tokenService.generateToken({userDto});
payload токена делается из полей класса userDto, который не содержат поля пароль

2024-09-11 10:26 UTC, Dmitry-Vasilyev commented on server/services/UserService.js
> +        if(!refreshToken) {
исправлено

2024-09-11 10:37 UTC, Dmitry-Vasilyev commented on server/services/UserService.js
> +        if(!userData || !tokenFromDB) {
исправлено

2024-09-11 10:39 UTC, Dmitry-Vasilyev commented on server/services/UserService.js
> +        const userDB = await UserModel.findOne(userData.id);
исправлено

2024-09-11 17:21 UTC, Dmitry-Vasilyev commented on server/services/UserService.js
> +        const users = await UserModel.find();
метод заменил на getUsers с пагинацией

2024-09-12 08:37 UTC, Dmitry-Vasilyev commented on server/utils/HashUtil.js
> +        const saltRounds = 10;
исправлено

2024-09-13 19:43 UTC, arnokay commented on server/Application/Application.js
> +        this.tokenService = new TokenService();
забыл это.

2024-09-13 19:52 UTC, arnokay commented on server/controllers/UserController.js
> +            console.log(e);
забыл это.

2024-09-13 19:57 UTC, arnokay commented on server/Application/Application.js
> +                    authMiddleware = require('../middleware/authMiddleware')} = {}) {
так делать не надо, лучше:
```js
const DefaultUserController = require('../controllers/UserController')
//...
UserController = DefaultUserController
```

2024-09-13 19:57 UTC, arnokay commented on server/Application/Application.js
> +                    authMiddleware = require('../middleware/authMiddleware')} = {}) {
гораздо понятнее зачем так сделано.

2024-09-13 20:13 UTC, arnokay requested changes
ещё два момента.

2024-09-14 11:57 UTC, arnokay approved these changes
можно мёрджить.

2024-09-14 12:14 UTC, merged